#!/bin/bash

if [ $USER != 'root' ]; then
    echo 'You must be root!'
    exit 1
fi

if [ ! $1 ]; then
    echo 'You must supply an argument:'
    echo './INSTALL { slatectl | slated }'
    echo ''
    echo 'Use ./INSTALL slatectl to install the SlateKV CLI tool'
    echo 'Use ./INSTALL slated to install the SlateKV server'
    exit 1
fi

if [ $1 == 'slatectl' ]; then
    DIR=/etc/slate
    mkdir $DIR
    cp slatectl $DIR/.
    cp slatectl.conf $DIR/.
    ln -s $DIR/slatectl /usr/bin/slatectl
fi

if [ $1 == 'slated' ]; then
    DIR=/var/run/slated
    mkdir $DIR
    mkdir /etc/slated
    cp slated $DIR/.
    cp slated.conf /etc/slated/.
    cp slated.service /usr/lib/systemd/system/.
    systemctl daemon-reload
    yum install -y python-pip || apt-get python-pip
    pip install flask
    pip install pymongo
    echo 'Enable the slated daemon by typing "systemctl enable slated"'
    echo 'Start the slated daemon by typing "systemctl start slated"'
    echo ''
    echo 'Enjoy :)'
fi

exit 0
